/* Generated By:JJTree: Do not edit this line. ASTClass.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTClass extends SimpleNode {
  private String name;

  public ASTClass(int id) {
    super(id);
  }

  public ASTClass(JavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  public void setName(String name){
    this.name = name;
  }

  @Override
  public String toString() {
    return super.toString() + " name: " + name;
  }
}
/* JavaCC - OriginalChecksum=577fcdf685c187d6124add0697408293 (do not edit this line) */
