/* Generated By:JJTree: Do not edit this line. ASTmethod.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTmethod extends SimpleNode {
  private String methodName, returnName;
  public ASTmethod(int id) {
    super(id);
  }

  public ASTmethod(JavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  public void setMethodName(String methodName){
    this.methodName = methodName;
  }

  public void setReturnName(String returnName){
    this.returnName = returnName;
  }

  @Override
  public String toString() {
    return super.toString() + " name: " + methodName + " return: " + returnName;
  }
}
/* JavaCC - OriginalChecksum=08c65ec30b4c1eaf2b78196cbaa0fc45 (do not edit this line) */
