/* Generated By:JJTree: Do not edit this line. ASTargs.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */

import java.util.ArrayList;
public class ASTargs extends SimpleNode {
  private ArrayList<String> typeName, name;
  public ASTargs(int id) {
    super(id);
    typeName = new ArrayList<>();
    name = new ArrayList<>();
  }

  public ASTargs(JavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  public void addType(String typeName){
    this.typeName.add(typeName);
  }

  public void addName(String name){
    this.name.add(name);
  }

  @Override
  public String toString() {
    return super.toString() + " " + getValues();
  }

  private String getValues(){
    String nameString = "";
    for (int i = 0; i < name.size(); i++){
      nameString += "name: " + name.get(i) + " type: " + typeName.get(i) + ", ";
    }
    return nameString;
  }
}
/* JavaCC - OriginalChecksum=8031c545f3b3917eef9b11f42afeb73f (do not edit this line) */
