/* Generated By:JJTree: Do not edit this line. ASTexp.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTexp extends SimpleNode {
  private String name;
  public ASTexp(int id) {
    super(id);
  }

  public ASTexp(JavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  public void addName(String name){
    this.name = name;
  }

  @Override
  public String toString() {
    return super.toString() + " name: " + name;
  }
}
/* JavaCC - OriginalChecksum=0678e3d8cab1805f2dbdde4d5be2880b (do not edit this line) */
