/* Generated By:JJTree: Do not edit this line. ASTifstmt.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTifstmt extends SimpleNode {
  public ASTifstmt(int id) {
    super(id);
  }

  public ASTifstmt(JavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d0d2d25ae0a8b70edaa5ca7be60a73cc (do not edit this line) */
