/* Generated By:JJTree: Do not edit this line. ASTmain.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTmain extends SimpleNode {
  private String name;
  private boolean hasArgs;

  public ASTmain(int id) {
    super(id);
  }

  public ASTmain(JavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  public void setName(String name){
    this.name = name;
  }

  public void setHasArgs(Boolean hasArgs){
    this.hasArgs = hasArgs;
  }
  @Override
  public String toString() {
    return super.toString() + " name:" + name + " has args: " + hasArgs;
  }
}
/* JavaCC - OriginalChecksum=3c16d3278cc12268d1aae2ca5adf661f (do not edit this line) */
