/* Generated By:JJTree: Do not edit this line. ASTtype.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTtype extends SimpleNode {
  private String typeName, name;
  public ASTtype(int id) {
    super(id);
  }

  public ASTtype(JavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  public void setType(String typeName){
    this.typeName = typeName;
  }

  public void setName(String name){
    this.name = name;
  }

  @Override
  public String toString() {
    return super.toString() + " name: " + name + " typeName: " + typeName;
  }
}
/* JavaCC - OriginalChecksum=081a5cacccec7ffb2e3e86e80eb23be4 (do not edit this line) */
