/* Generated By:JJTree: Do not edit this line. ASTwhilestmt.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTwhilestmt extends SimpleNode {
  public ASTwhilestmt(int id) {
    super(id);
  }

  public ASTwhilestmt(JavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5122cb61ae9938e47ca81a057ec93fdb (do not edit this line) */
