/* Generated By:JavaCC: Do not edit this line. JavaParserTreeConstants.java Version 4.1d1 */
public interface JavaParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTMAIN = 2;
  public int JJTCLASS = 3;
  public int JJTTYPE = 4;
  public int JJTARGS = 5;
  public int JJTMETHOD = 6;
  public int JJTIFSTMT = 7;
  public int JJTWHILESTMT = 8;
  public int JJTEXP = 9;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "main",
    "Class",
    "type",
    "args",
    "method",
    "ifstmt",
    "whilestmt",
    "exp",
  };
}
/* JavaCC - OriginalChecksum=e6910d459f138d2341eb46c894dbd2c9 (do not edit this line) */
