/* Generated By:JavaCC: Do not edit this line. JavaParserVisitor.java Version 4.1d1 */
public interface JavaParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTmain node, Object data);
  public Object visit(ASTClass node, Object data);
  public Object visit(ASTtype node, Object data);
  public Object visit(ASTargs node, Object data);
  public Object visit(ASTmethod node, Object data);
  public Object visit(ASTifstmt node, Object data);
  public Object visit(ASTwhilestmt node, Object data);
  public Object visit(ASTexp node, Object data);
}
/* JavaCC - OriginalChecksum=2408819e3c3bd640862356598fb9d1ca (do not edit this line) */
